parameters:
    database_driver: pdo_mysql
    database_host: remote-mysql3.servage.net
    database_port: null
    database_name: lifereminder
    database_user: lifereminder
    database_password: passwords123
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 4b08d4c909e30ea255092f12683903f388c9982c
    database_path: null
