<?php

namespace Mk\LifeReminder\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * userstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userstatusRepository extends EntityRepository
{
}
